DWAPlannerROS:
  # Robot Configuration Parameters
  max_vel_x: 0.25
  min_vel_x: 0.1
  max_vel_theta: 1.0
  min_vel_theta: 0.3
  min_in_place_vel_theta: 0.4

  acc_lim_theta: 3.2
  acc_lim_x: 1.5
  acc_lim_y: 0.0

  holonomic_robot: false

  # Goal Tolerance Parameters
  yaw_goal_tolerance: 0.25
  xy_goal_tolerance: 0.25
  latch_xy_goal_tolerance: false

  # Forward Simulation Parameters
  sim_time: 2.0
  vx_samples: 20
  vy_samples: 0
  vtheta_samples: 40

  # Trajectory Scoring Parameters
  path_distance_bias: 32.0
  goal_distance_bias: 24.0
  occdist_scale: 0.03
  forward_point_distance: 0.325

  # Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05

  # Debugging
  publish_traj_pc: true
  publish_cost_grid_pc: true

  # Differential-drive robot configuration
  holonomic_robot: false
